### ISSUE TITLE
Blank page in Tenant Manager

### ISSUE THREAD

**Issue by GillesK** [mayocat/mayocat-shop#221]
Hello,
I´ve installed the 0.30.1 and managed to make it function on windows thru cygwin
I then activated the multi-tenant feature.
When accessing localhost:8080/manager i just get a blank page in chrome and IE.

I get in Chrome debugging: jquery.min.map (with a bizarre path) -> ERR_FILE_NOT_FOUND

**Comment by jvelo** [comment]
I could not reproduce on 0.40-SNAPSHOT. Closing for now, please reopen if this issue rises again when 0.40 is released.
